# Generated by Django 5.1.2 on 2024-10-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Utilities', 'Utilities'), ('Housing', 'Housing'), ('Subscriptions', 'Subscriptions'), ('Health care', 'Health care'), ('Donations', 'Donations'), ('Entertainment', 'Entertainment')], default='Food', max_length=50)),
                ('type', models.CharField(help_text='Enter the type of expenditure (e.g., grocery, taxi, etc.)', max_length=100)),
                ('date', models.DateField(help_text='Enter the date of the expenditure')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the amount of expenditure', max_digits=10)),
            ],
        ),
    ]
