# Generated by Django 5.1.2 on 2024-10-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', models.CharField(choices=[('Salary/Wages', 'Salary/Wages'), ('Business Income', 'Business Income'), ('Rental Income', 'Rental Income'), ('Investment Income', 'Investment Income'), ('Pension/Retirement Income', 'Pension/Retirement Income'), ('Interest Income', 'Interest Income'), ('Royalties', 'Royalties'), ('Freelance/Contractor Income', 'Freelance/Contractor Income'), ('Government Benefits', 'Government Benefits'), ('Dividends', 'Dividends'), ('Capital Gains', 'Capital Gains'), ('Annuities', 'Annuities'), ('Gifts/Inheritance', 'Gifts/Inheritance'), ('Other', 'Other')], max_length=50)),
                ('income_source', models.CharField(max_length=255)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_date', models.DateField()),
                ('income_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
