# Generated by Django 5.1.2 on 2024-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_category', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Online', 'Online'), ('Export', 'Export'), ('Other', 'Other')], default='Retail', help_text='Select the category of sales', max_length=50)),
                ('product_name', models.CharField(help_text='Enter the name of the product or service', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Enter the quantity of the product or service')),
                ('sales_amount', models.DecimalField(decimal_places=2, help_text='Enter the total sales amount', max_digits=10)),
                ('sales_date', models.DateField(help_text='Enter the date of the sale')),
                ('description', models.TextField(blank=True, help_text='Optional description of the sale')),
            ],
        ),
    ]
