# Generated by Django 5.1.2 on 2024-10-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_address',
            field=models.CharField(blank=True, help_text='Enter the address of the customer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(default='Unknown', help_text='Enter the name of the customer', max_length=100),
        ),
    ]
