# Generated by Django 5.1.2 on 2024-10-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sales_customer_address_sales_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='Enter the name of the vendor', max_length=100)),
                ('purchase_category', models.CharField(choices=[('Office Supplies', 'Office Supplies'), ('Equipment', 'Equipment'), ('Utilities', 'Utilities'), ('Raw Materials', 'Raw Materials'), ('Miscellaneous', 'Miscellaneous')], help_text='Select the category of the purchase', max_length=50)),
                ('purchase_date', models.DateField(help_text='Enter the date of the purchase')),
                ('product_name', models.CharField(help_text='Enter the name of the product or service purchased', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Enter the quantity of the product or service')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the total purchase amount', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], help_text='Select the payment status', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the purchase', null=True)),
            ],
        ),
    ]
